
GET http://localhost:3000/

###
GET http://localhost:3000/api/books/

###
GET http://localhost:3000/api/books/1586543168911

###
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "name": "The Half-Blood Prince",
    "author": "J. K. Rowling",
    "year": 2005
}

###
PUT http://localhost:3000/api/books/1586543106811
Content-Type: application/json

{
    "name": "The Chamber of Secrets",
}

###
DELETE http://localhost:3000/api/books/1586543124830
